language: node_js
# changed to node 14
node_js:
  - "14"

before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt update
  - sudo apt-get install -y python3.6
  - which python3
  - python3 --version
  - npm i -g npm
  - npm config set python=/opt/pyenv/shims/python3

# Cache node dependencies
cache:
  directories:
    - bower_components
